### PR TITLE
[DNM][disallow secrets] Test on Status 

### PR DESCRIPTION
**Pull request by Yikun**
image

Let's see what happened when disallow `edits and access to secrets by maintainers` in pr.

### CODE REVIEW

**Comment by HyukjinKwon** [comment]
Seems like being updated fine!
Screen Shot 2021-04-16 at 2 05 02 PM

**Comment by HyukjinKwon** [comment]
Nice!
Screen Shot 2021-04-16 at 2 36 32 PM

**Comment by Yikun** [comment]
image

image

Triggered and url is expected now, let's see what will be happened for a while

**Comment by HyukjinKwon** [comment]
This is a good example of a failure :-)

**Comment by HyukjinKwon** [comment]
apache/spark#32193 merged. Closing

**Pull request closed without merging**
